#+TITLE: emacs实践笔记
#+AUTHOR: aborn
#+DATE: 2016-10-30 17:28
#+EMAIL: aborn.jiang@gmail.com
#+LANGUAGE: zh
#+LATEX_HEADER: \usepackage{xeCJK}

#+SETUPFILE: ~/github/org-html-themes/setup/theme-readtheorg.setup-----

* emacs的书签功能
emacs的书签功能可以保存光标的位置

** 设置一个书签
 *bookmark-set* 对应快捷键为 *C-x r m*

** 列出保存的书签
 *bookmark-bmenu-list* 对应快捷键为 *C-x r l* ，它将打开一个*Bookmark List*的buffer同时
列出所有保存的书签。

*** 书签列表Buffer*Bookmark List*
在*Bookmark List*这个buffer里，有以下快捷键可以使用：
- a 显示当前书签的标注信息
- A 在另一个buffer中显示所有书签的所有标注信息
- d 标记书签，以便用来删除 (x – 执行删除)
- e 编辑当前书签的标注信息
- m 标记书签，以便用于进一步显示和其他操作 (v – 访问这个书签)
- o 选中当前书签，并显示在另一个window中
- C-o 在另一个window中切换到当前这个书签
- r 重命名当前书签
- w 将当前书签的位置显示在minibuffer里

** 跳转到一个书签
使用 *bookmark-jump* 函数，可以跳转到一个特定的书签，它绑定的快捷键为 *C-x r b* 。
如果你的emacs中安装了[[https://github.com/emacs-helm/helm][helm]] 这个插件，你也可以使用 *helm-bookmarks* 这个命令
来快速查找书签，并跳转到书签位置。

*** 修改默认排序
要书签查找和跳转的时候，默认的书签排序是按字母排序的。如果想将最近访问的书签放在最前面，
将下面代码添加到你的emacs配置文件中。
#+NAME: 修改默认排序
#+BEGIN_SRC emacs-lisp
(defadvice bookmark-jump (after bookmark-jump activate)
  (let ((latest (bookmark-get-bookmark bookmark)))
    (setq bookmark-alist (delq latest bookmark-alist))
    (add-to-list 'bookmark-alist latest)))
#+END_SRC

** 删除一个书签
删除一个书签对应的命令为 *bookmark-delete* 。

** 保存书签
在最新版本（老版本的bookmark保存在 *~/.emacs.bmk* ），
emacs在退出的时候会自动保存书签。如果想手动保存书签的话，可以采用
 *bookmark-save* 这个函数命令。默认的情况，emacs会将书签保存在 *bookmark-default-file*
变量对应的文件中。在我的机器中，对应的文件如下：
#+NAME: 书签文件路径
#+BEGIN_SRC emacs-lisp
ELISP> bookmark-default-file
"/Users/aborn/.emacs.d/.cache/bookmarks"
ELISP>
#+END_SRC

** 其他设置
有一个变量 *bookmark-save-flag* 。如果这个变量的值为一个数值，它表示修改（添加）
多少次bookmark后会自动保存一次。当这个变量的值为被设置为1时，每次对bookmark的改
动，emacs就会自动保存内容到磁盘相应位置（这样可以防止emacs突然crash时bookmark的丢失）。
如果这个值设置为nil，表示emacs不会主动保存bookmark，除非用户手动调用
*M-x bookmark-save* 。

* dired模式
dired的全称为Directory Edit，即目录编辑，是一个非常老的模式。
* 常用命令
** 移动命令
 *n* 下移
 *p* 上移
** 编辑命令
 *R* 重命名或者移动文件
 *D* 删除文件或者目录
 *+* 创建目录
 *Z* gzip压缩文件
** 其他命令
 *RET* 打开文件或者目录
 *q*   退出

* magit模式简介
magit是emacs下版本管理的强大武器

* 常用命令
 *magit-diff* 相当于git diff, 当进入diff-buffer后按g更新之
 *magit-status* 相当于git status, 进入status-buffer后按s添加文件或文件夹到本地仓库

* org模式简介
Emacs的org-mode可用于记笔记、管理自己的待办事项(TODO lists)，同时，也可用于管理项目。它是一种高效的纯文本编辑系统。

* 文档结构
Org是基于Outline-mode，并提供灵活的命令编辑结构化的文档。其文档结构语法跟markdown很类似。
** 目录结构
Org的目录结构在每行最左边以星号标记，星号越多，标题层级越深。下面是一些例子：

#+BEGIN_EXAMPLE
\* 一级目录
\** 二级目录
\*** 三级目录

\* 另一个一级目录
#+END_EXAMPLE

** 显示与隐藏
目录结构下的内容可以隐藏起来，通常用采用 *TAB* 和 /S-TAB/ 这两个命令来切换。

** 列表
Org提供三种类型的列表：有序列表、无序列表和描述列表
1. 有序列表以'1.' 或者 '1)'
2. 无序列表以'-', '+' 或者 '*'
3. 描述列表

** 块结构
在Org文档中，加入代码块这种类型的块结构，都是采用begin...end这种模式，下面是一个例子：

#+BEGIN_EXAMPLE
\#+BEGIN_EXAMPLE
\#+END_EXAMPLE
#+END_EXAMPLE

* 表格
* 超链接
Org模式提供了比较好用的超链接方式，可以链接到普通网页、文件、email等。
** 链接格式
Org模式支持两种链接，即，内部链接和外部链接。它们有相同的格式：
#+BEGIN_EXAMPLE
[[链接][描述]]  或 当只有链接没有描述  [[链接]]
#+END_EXAMPLE
一旦链接编辑完成，在org模式下，只显示 *描述* 部分，而不会显示整体（后一种是只显示链接）。
为了编辑链接和描述，需要通过快捷键 *C-c C-l* 来完成。
*** 内部链接
内部链接是指向当前文件的链接,它的链接格式:
#+BEGIN_EXAMPLE
[[#链接ID]]
#+END_EXAMPLE
其中 *链接ID* 是文档中唯一的标识ID

*** 外部链接
外部链接有很多中形式，最常见的形式是网页链接

* 待办事项
Org模式用来管理自己的TODO list非常方便

* 包列表
1. elisp-slime-nav 写elisp代码时，可用于跳转到函数的定义
