#+TITLE: 文件
#+AUTHOR: aborn
#+DATE: 2018-04-08
#+EMAIL: aborn.jiang@gmail.com
#+LANGUAGE: zh
#+LATEX_HEADER: \usepackage{xeCJK}

#+SETUPFILE: ~/github/org-html-themes/setup/theme-readtheorg.setup

-----

* 文件及访问
  文件是操作系统永久保存数据的单元，为了编辑文件，我们必要告诉Emacs去读取一个文件，并将文件的内
  容保存在一个Buffer里，这样Buffer与文件就关联在一起。下面介绍与文件访问相关的函数，由于历史原
  因这些函数的命令都是以 *find-* 开头的，不是以 *visit-* 开头。

** 打开文件
   如果想在buffer里打开一个文件，其命令是 *find-file* (C-x C-f)。当文件已经在buffer中存在时，
   这个命令返回文件对应的buffer。如果当前没有buffer对应文件，则，创建一个buffer，并将其文件
   内容读到buffer中，并返回这个buffer。字义如下:

   #+BEGIN_SRC emacs-lisp
   find-file filename &optional wildcards
   #+END_SRC

   这个函数有一个对应的hook变量，叫 *find-file-hook* 它的值是一个函数列表。这些函数在文件被
   打开后依次执行。

** 文件保存
   文件被载入到buffer后，我们可以对其进行修改；修改完了后，将内容保存回文件，其对应的函数为：

   #+BEGIN_SRC emacs-lisp
   save-buffer &optional backup-option
   #+END_SRC

   文件保存对应有两个hook变量，为： *before-save-hook* 和 *after-save-hook* 分别表示保
   存前的hook函数列表和保存后的hook函数列表。与之类似的还有一个函数 *write-file*

   #+BEGIN_SRC emacs-lisp
   write-file  filename &optional confirm
   #+END_SRC
   这个函数的功能是将当前buffer的内容写入到filename对应的文件中，并将当前buffer与这个文件进
   行关联

** 读取文件内容(Reading from Files)
   将文件内容复制到buffer，可以使用 *insert-file-contents* 函数，注意在Lisp代码里不要使用
   *insert-file* 命令，因为它会设置mark标识。

   #+BEGIN_SRC emacs-lisp
   (insert-file-contents filename &optional visit beg end replace)
   #+END_SRC
   这个函数在当前buffer的位置插入文件 *filename* 的内容，它返回一个list，它包含一个文件名和
   数据长度信息。如果文件不存在，则会抛出错误异常!

** 往文件里写内容(Writing to Files)
   将buffer里的内容（或者部分内容）直接写入到一个文件，可以采用 *append-to-file* 和 *write-region*
   函数。注意这里不要写入正在访问的文件，否则会出现异常情况：

   #+BEGIN_SRC emacs-lisp
   (append-to-file start end filename)
   #+END_SRC
   这个函数的作用是将当前buffer里的部分内容（从start到end部分内容）追加到文件 *filename* 的
   后面。如果是在lisp中使用，这个函数完全等价于 (write-region start end filename t)。

   #+BEGIN_SRC emacs-lisp
   (write-region start end filename &optional append visit lockname mustbenew)
   #+END_SRC
   这个函数的作用与append-to-file类似，不过其参数更多。
   1. 当start为nil时，这个函数写入的是当前buffer所有内容，这时end参数没有用;
   2. 当start为string时，这个函数写入的内容是string的内容，这时end参数失效;
   3. 当append不是nil时，表示往现有文件里进行追加，当append是一个数字时，表示从当前文件开始到
   append的位置开始写入。
   4. 当mustbenew不为nil时，当覆盖已有文件时，会询问用户，并获得用户确定后再操作。

   #+BEGIN_SRC emacs-lisp
   (with-temp-file file body)
   #+END_SRC
   *with-temp-file* 是一个宏操作，它将创建一个临时buffer作为当前buffer，在这个buffer里对
   body进行求值，最后将这个buffer的内容写入到文件 *file* 里。当整个body执行完成后，Emacs将
   会把这个临时buffer关闭，恢复到执行with-temp-file之前的当前buffer。它将body的最后执行结
   果作为with-temp-file的返回结果。

* 文件基本信息函数
  下面介绍一些与文件基本信息相关的函数

  1. 文件是否存在

  #+BEGIN_SRC emacs-lisp
  file-exists-p  lename
  #+END_SRC
  与之类似的有: *file-readable-p* 、 *file-executable-p* 、 *file-writable-p* 、
  *file-directory-p* 这几个函数。

**  文件属性
   这小节介绍与文件属性有关的一些函数，如文件的所属人、所属组、文件大小、文件的最新读取和修改时
   间等。
   1. 文件新旧比较
      #+BEGIN_SRC emacs-lisp
      file-newer-than-file-p filename1 filename2
      #+END_SRC
   当filename1比filename2新时，该函数返回t。如果filename1不存在，则返回nil。如果filename1
   存在，但filename2不存在，则返回t。


* 文件与目录
  判断文件是否在一个目录下，怎么做?

  #+BEGIN_SRC emacs-lisp
  file-in-directory-p  file dir
  #+END_SRC

  如果file是一个在目录dir或者dir子目录下的文件，则返回t。如果file与dir处于同一目录，也返回t。
  如果想列出一个目录下的所有文件，那就要用到 *directory-files* 这个函数，其定义如下：

  #+BEGIN_SRC emacs-lisp
  directory-files directory &optional full-name match-regexp nosort
  #+END_SRC

  这个函数按字母顺序返回目录 directory 下的所有文件。参数 full-name 不为nil时，则返回每个文
  件的绝对路径，否则返回相对路径。match-regexp 如果不是nil，该函数返回只与match-regexp相匹
  配的文件列表。nosort如果不为nil，则不按字母排序。

** 创建、复制和删除目录
   对目录的创建、复制和删除都有相关的处理函数，下面一一介绍：

   #+BEGIN_SRC emacs-lisp
   make-directory dirname &optional parents
   #+END_SRC
   *make-directory* 创建一个目录名为dirname的目录

* 文件名
  下面介绍一些与文件名操作有关的函数

  #+BEGIN_SRC emacs-lisp
  file-name-directory  lename
  #+END_SRC

  *file-name-directory* 返回的文件名里的目录部分，如果文件名里没有包含目录部分，则返回nil。
  与这个函数对应的一个函数为 *file-name-nondirectory* ，它返回非目录部分。

** 文件名扩展
   *expand-file-name* 这个函数将文件名转成绝对文件名：

   #+BEGIN_SRC emacs-lisp
   expand-file-name filename &optional directory
   #+END_SRC

   如果directory参数存在，将filename作为其相对路径，否则使用 *default-directory* 变量。
   这个函数在写elisp代码时经常用到，下面是一些例子:

   #+BEGIN_SRC emacs-lisp
   (expand-file-name "foo")
   ⇒ "/xcssun/users/rms/lewis/foo"
   (expand-file-name "../foo")
   ⇒ "/xcssun/users/rms/foo"
   (expand-file-name "foo" "/usr/spool/") ⇒ "/usr/spool/foo"
   #+END_SRC
