#+TITLE: org 实践
#+AUTHOR: aborn
#+DATE: 2016-10-12
#+EMAIL: aborn.jiang@gmail.com
#+LANGUAGE: zh
#+LATEX_HEADER: \usepackage{xeCJK}

#+SETUPFILE: ~/github/org-html-themes/setup/theme-readtheorg.setup

-----
* org模式简介
Emacs的org-mode可用于记笔记、管理自己的待办事项(TODO lists)，同时，也可用于管理项目。它是一个高效的纯文本编辑系统。

* 文档结构
Org是基于Outline-mode，并提供灵活的命令编辑结构化的文档。其文档结构语法跟markdown很类似。
** 目录结构
Org的目录结构在每行最左边以星号标记，星号越多，标题层级越深。下面是一些例子：

#+BEGIN_EXAMPLE
\* 一级目录
\** 二级目录
\*** 三级目录

\* 另一个一级目录
#+END_EXAMPLE

** 显示与隐藏
目录结构下的内容可以隐藏起来，通常用采用 *TAB* 和 /S-TAB/ 这两个命令来切换。

** 列表
Org提供三种类型的列表：有序列表、无序列表和描述列表
1. 有序列表以'1.' 或者 '1)'
2. 无序列表以'-', '+' 或者 '*'
3. 描述列表

** 块结构
在Org文档中，加入代码块这种类型的块结构，都是采用begin...end这种模式，下面是一个例子：

#+BEGIN_EXAMPLE
\#+BEGIN_EXAMPLE
\#+END_EXAMPLE
#+END_EXAMPLE

* 表格
* 超链接
Org模式提供了比较好用的超链接方式，可以链接到普通网页、文件、email等。
** 链接格式
Org模式支持两种链接，即，内部链接和外部链接。它们有相同的格式：
#+BEGIN_EXAMPLE
[[链接][描述]]  或 当只有链接没有描述  [[链接]]
#+END_EXAMPLE
一旦链接编辑完成，在org模式下，只显示 *描述* 部分，而不会显示整体（后一种是只显示链接）。
为了编辑链接和描述，需要通过快捷键 *C-c C-l* 来完成。
*** 内部链接
内部链接是指向当前文件的链接,它的链接格式:
#+BEGIN_EXAMPLE
[[#链接ID]]
#+END_EXAMPLE
其中 *链接ID* 是文档中唯一的标识ID

*** 外部链接
Org支持的外部链接有很多中形式，如文件、网页、新闻组、电子邮件信息、BBDB数据条目等。
它们以一个短的标识字符串打头，紧接着是一个冒号，冒号后面没有空格字符。

*** 链接处理相关命令

+ org-store-link 保存当前位置的一个链接，以备后面插入使用
+ org-insert-link 插入链接，绑定的快捷键为C-c C-l，如果光标正在一个链接上，那么C-c C-l的行为是编辑这个链接及其描述

* 待办事项
Org模式用来管理自己的TODO list非常方便

* 日程表(Agenda View)
我们可以用Org来按排自己的行程

** 日程文件(Agenda files)
变量org-agenda-files保存了一个文件列表,这些文件用来记录日程，下面是一些操作函数:
C-c [ 将当前文件加入到agenda文件列表最前页面 org-agenda-file-to-front
C-c ] 将当前文件从agenda文件列表中删除 org-remove-file

** 分发按键
默认采用 *C-c a* ,接下的默认的命令有：

+ a   创建一个日程
+ t/T 创建一个TODO items
+ L   对当前文件生成timeline

** 内建Agenda视图

** 计划Schedule
相关命令

+ org-schedule 将当前TODO添加计划时间
